Feat/alta eventos
JavaMoment/WebSide pull request #58
Opened 2024-05-27 21:42 UTC by romicaubarrere

2024-05-29 23:44 UTC, redex22 requested changes
sacando el par de detalles comentados, LGTM. Nice work!

2024-05-29 23:44 UTC, redex22 commented on src/main/webapp/views/login.xhtml
> +				<p:commandButton value="Registrarme" update="msgs"
sin el listener no sucede el registro de usuario je

2024-05-29 23:44 UTC, redex22 commented on src/main/webapp/views/login.xhtml
> +						<p:inputText id="email" placeholder="Correo utec"
tmb se puede ingresar por nombre de usuario

2024-06-03 13:38 UTC, romicaubarrere commented on src/main/webapp/views/login.xhtml
> +				<p:commandButton value="Registrarme" update="msgs"
che esto se puede editar aca o hago otro pr?

2024-06-10 21:31 UTC, closed without merging