Feat/listado auxiliar estados eventos
JavaMoment/WebSide pull request #62
Opened 2024-06-04 20:23 UTC by romicaubarrere

2024-06-05 15:10 UTC, redex22 commented on src/main/webapp/views/static/templates/home.xhtml
> +				</a>
ver de agregarlo al contexto de eventos

2024-06-05 15:18 UTC, redex22 requested changes
arreglando eso looks good really good

2024-06-05 15:18 UTC, redex22 commented on src/main/webapp/views/static/events/eventsList.xhtml
> +								sortBy="#{event.evento.fechaHoraFinal}"
debe el atributo ser evento (like esta declarado dentro del tag  p:datatable "var="

2024-06-05 15:19 UTC, redex22 commented on src/main/java/com/controllers/events/AddEstadoView.java
> +//	        context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "¡Bien!", "El Estado " + newEstado.getNombre() + " ha sido correctamente añadido."));
borrar lineas sin uso

2024-06-05 15:28 UTC, redex22 commented on src/main/java/com/controllers/events/test.java
borrar isso cara tas burneando to

2024-06-06 21:22 UTC, romicaubarrere commented on src/main/webapp/views/static/templates/home.xhtml
> +				</a>
listorti

2024-06-06 21:29 UTC, romicaubarrere commented on src/main/webapp/views/static/events/eventsList.xhtml
> +								sortBy="#{event.evento.fechaHoraFinal}"
arreglado

2024-06-06 21:30 UTC, romicaubarrere commented on src/main/java/com/controllers/events/AddEstadoView.java
> +//	        context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "¡Bien!", "El Estado " + newEstado.getNombre() + " ha sido correctamente añadido."));
tuki

2024-06-06 21:30 UTC, romicaubarrere commented on src/main/java/com/controllers/events/test.java
se fue quemadisimo

2024-06-10 21:31 UTC, closed without merging